{
  "formatVersion": "1.1",
  "component": {
    "group": "com.autonomi",
    "module": "ant-android",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.14.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jna",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "ant-android-0.0.4.aar",
          "url": "ant-android-0.0.4.aar",
          "size": 37839908,
          "sha512": "cfbcec7f4d6bac8220d7cc26100a1f8d5606b6e0b6364a957bd58b5b13e5ccc0f83fb45dc6ba8099b0af72bda8cc64cb1f481911cd0505b80f1cecbd843377e9",
          "sha256": "f6807d057d2726ecdcb04b0faa456723ca22f57318b261401cbfe0cfe2a5e2d5",
          "sha1": "732e44708006958eaccf3515d7b9d9a5c8f061d0",
          "md5": "a602f6c934d10e75162d8a1a30e1d3a9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.14.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jna",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "ant-android-0.0.4.aar",
          "url": "ant-android-0.0.4.aar",
          "size": 37839908,
          "sha512": "cfbcec7f4d6bac8220d7cc26100a1f8d5606b6e0b6364a957bd58b5b13e5ccc0f83fb45dc6ba8099b0af72bda8cc64cb1f481911cd0505b80f1cecbd843377e9",
          "sha256": "f6807d057d2726ecdcb04b0faa456723ca22f57318b261401cbfe0cfe2a5e2d5",
          "sha1": "732e44708006958eaccf3515d7b9d9a5c8f061d0",
          "md5": "a602f6c934d10e75162d8a1a30e1d3a9"
        }
      ]
    }
  ]
}
