{
  "formatVersion": "1.1",
  "component": {
    "group": "com.autonomi",
    "module": "ant-android",
    "version": "0.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.14.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jna",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "ant-android-0.0.5.aar",
          "url": "ant-android-0.0.5.aar",
          "size": 38341092,
          "sha512": "9e97c66a65bf079efb127ecb9fbe216fb13776962aed9e3f5100e8c854f299de251099d38c81020a6e39c2ec35a910cef181855f51c1cd6f501a9d088378156e",
          "sha256": "4d3aa32bb6bc5a7905c05da4c78fc18ef0ec90bd812688166315339fe3b7108c",
          "sha1": "2be7860300320c1d444157b019f3d629980167b4",
          "md5": "2498a9caa0e688cc735360100b75c9fb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.14.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jna",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "ant-android-0.0.5.aar",
          "url": "ant-android-0.0.5.aar",
          "size": 38341092,
          "sha512": "9e97c66a65bf079efb127ecb9fbe216fb13776962aed9e3f5100e8c854f299de251099d38c81020a6e39c2ec35a910cef181855f51c1cd6f501a9d088378156e",
          "sha256": "4d3aa32bb6bc5a7905c05da4c78fc18ef0ec90bd812688166315339fe3b7108c",
          "sha1": "2be7860300320c1d444157b019f3d629980167b4",
          "md5": "2498a9caa0e688cc735360100b75c9fb"
        }
      ]
    }
  ]
}
